language: node_js
node_js:
- node
before_script:
- echo -e "Host exane.cf\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_342f2f6ad141_key -iv $encrypted_342f2f6ad141_iv -in .travis/travis_rsa.enc -out ~/.ssh/travis_rsa -d
deploy:
- provider: script
  skip_cleanup: true
  script: bash .travis/deploy.sh
  on:
    branch: master
