name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, build, and test
      run: |
        yarn
        yarn test
      env:
        CI: true
    - name: deploy
      if: github.ref == 'master'
      run: |
        chmod +x ./.github/decrypt_secret.sh
        ./.github/decrypt_secret.sh
        git checkout ./.github/decrypt_secret.sh
        yarn run deploy
      env:
        ENCRYPTION_SECRET: ${{ secrets.ENCRYPTION_SECRET }}
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock